# -*- coding: utf-8 -*-
"""Copy of project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_ipnEYSchdG3Fx18Wh3-OeB7vWULB8jY
"""

celsius=int(input("Enter the temprature in celsius:"))
fahrenhit=(celsius*9/5)+32
print(celsius, " Celsius is :")
print(fahrenhit," Fahrenhit")